// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  mainSidebar: [
    {
      type: 'link',
      label: 'DriftGuard Enterprise',
      href: 'https://docs.limepoint.com/driftguard-enterprise',
    },
    {
      type: 'link',
      label: 'MintPress',
      href: 'https://docs.limepoint.com/mintpress',
    },
    {
      type: 'html',
      value: '<hr />',
      defaultStyle: true,
    },
    { type: 'autogenerated', dirName: '.' },
  ],
}

module.exports = sidebars
